apiVersion: v1
kind: PersistentVolume
metadata:
  name: notejam-pv
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/test"
    